# Generated by Django 2.2.6 on 2019-11-07 11:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0110_auto_20191107_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
