# Generated by Django 2.2.6 on 2019-11-08 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0111_auto_20191107_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=12, null=True),
        ),
    ]
