# Generated by Django 2.2.6 on 2019-11-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0018_auto_20190827_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='min_checkout_items_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
