# Generated by Django 2.2.6 on 2019-11-07 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20191018_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='quantity_fulfilled',
        ),
        migrations.AddField(
            model_name='orderline',
            name='quantity_fullfilled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fulfillmentline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
