# Generated by Django 2.2.6 on 2019-11-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0077_auto_20191107_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='quantity_fullfilled',
            new_name='quantity_fulfilled',
        ),
    ]
